from os import getenv

PHONE_IP=getenv("PHONE_IP")
VIDEO_PATH=getenv("VIDEO_PATH")
BG_PHOTO_PATH=getenv("BG_PHOTO_PATH")
DOWNSCALE_WIDTH=int(getenv("DOWNSCALE_WIDTH"))
DOWNSCALE_HEIGHT=int(getenv("DOWNSCALE_HEIGHT"))
